seek-oss/wingman

README.md
I’ve already reached semantic satiation with the name.
=> Document proposed design

fe/lib/components/private/DownloadLink/DownloadLink.tsx, fe/lib/components/private/DownloadLink/download.ts, fe/lib/components/private/TextLinkButton/TextLinkButton.tsx, fe/lib/components/private/index.ts, fe/package.json, fe/sku.config.js, yarn.lock
We use this for candidate profile attachments.
=> Add DownloadLink component

be/package.json, be/server/src/api/attachment.ts, be/server/src/api/index.ts, be/server/src/app.test.ts, be/server/src/app.ts, be/server/src/config.ts, be/server/src/localServer.ts, be/src/seekAttachment/middleware.ts, yarn.lock
And now the download links do something, albeit poorly!
=> Serve attachments from example backend

be/README.md, be/package.json, be/server/src/api/index.ts, be/server/src/app.ts, be/server/src/localServer.ts
This can be cURLed but CORS shenanigans are afoot. More soon.
=> Wire up SEEK proxy endpoint

fe/site/src/App/App.tsx, fe/site/src/App/HomePage.tsx, fe/site/src/App/Version.test.tsx, fe/site/src/App/Version.tsx, fe/site/src/api/constants.ts, fe/site/src/api/download.ts, fe/site/src/api/seekGraph.ts
My CORS woes magically dissipated.
This uses raw Fetch API at the moment; I’m going to play with Apollo Client 3 to see if it’s viable.
---
=> Retrieve version via SEEK proxy endpoint

fe/example/src/App/Webhook.tsx, fe/sku.config.js
=> Sort frontend imports

fe/example/src/App/App.tsx, fe/example/src/App/HomePage.test.tsx, fe/example/src/App/Webhook.tsx
This is way more fun than a plain old Alert.
=> Use toasts for webhook test interactions

.github/workflows/release.yml, README.md, package.json
I thought that the GitHub Action magically aliased changeset, but I guess not.
=> Fix version command

be/README.md, fe/README.md
- Add one-line descriptions of backend endpoints
- Document some headers
- Add npm badges
=> Tweak package READMEs

be/src/getPartnerToken.ts, be/src/partnerWebhook/middleware.test.ts, be/src/seekAttachment/middleware.ts, be/src/seekGraph/context.ts, be/src/seekGraph/schema.ts, be/src/testing/data/webhooks.ts, be/src/testing/mock.ts
This function signature needs to be revised but that will be for later.
=> Shuffle getPartnerToken

.github/workflows/release.yml
Per https://github.com/storybookjs/storybook-deployer/issues/77 fixes deploy error
=> fix: add actor/org to deploy token

.github/workflows/release.yml, fe/package.json
- We need to build storybook using the version exported by SKU in order for it to pick up the correct config.
=> fix: build storybook using 'sku' then deploy

be/example/src/api/index.ts, be/example/src/api/root.ts
This bundles some basic error handling and request logging together.
=> Add root middleware to example backend

be/example/src/api/browserToken.ts, be/example/src/api/index.ts, be/example/src/config.ts, fe/example/src/App/App.tsx, fe/example/src/App/Attachments.tsx, fe/example/src/App/HomePage.test.tsx, fe/example/src/api/browserToken.ts, fe/example/src/api/download.ts, fe/example/src/api/seekGraph.ts, fe/lib/components/private/DownloadLink/DownloadLink.tsx, fe/lib/hooks/BrowserToken/BrowserToken.tsx, fe/lib/hooks/BrowserToken/fetch.ts, fe/lib/hooks/BrowserToken/types.ts, fe/lib/hooks/index.ts, fe/lib/validation.ts
- Builds on #45
- Is currently blocked by CORS
=> Use browser tokens for example downloads

.changeset/heavy-icons-poke.md, be/.eslintrc.js, be/src/browserToken/middleware.test.ts, be/src/browserToken/middleware.ts, be/src/browserToken/types.ts, be/src/testing/tokens.ts, fe/example/src/App/Attachments.tsx, fe/lib/hooks/BrowserToken/BrowserToken.tsx, fe/lib/hooks/BrowserToken/fetch.ts, fe/lib/hooks/BrowserToken/types.ts, fe/lib/validation.ts, fe/package.json, fe/sku.config.js
- https://github.com/seek-oss/wingman/pull/46#discussion_r436318560
- We weren't caching by scope
=> Handle browser tokens better

fe/lib/components/QuestionnaireBuilder/app.stories.tsx, fe/lib/components/QuestionnaireBuilder/components/GraphqlQueryRenderer/GraphqlQueryRenderer.stories.tsx
Aligns structure of QuestionnaireBuilder stories to the current component structure
=> refactor: rename QuestionnaireBuilder storybook stories 

be/.dockerignore, be/.eslintignore, be/.eslintrc.js, be/.gitignore, be/.prettierignore, be/package.json, be/tsconfig.json, package.json, yarn.lock
This is a bit wonky because Wingman is a monorepo and also has both application and package code under each subdirectory.
=> Bump to skuba@3.7.3

CONTRIBUTING.md
- Align semver doco
- Point to proposed `#indirect` Slack channel
=> Tweak CONTRIBUTING.md

CONTRIBUTING.md
Too much change for one sentence.
=> Fix grammar in CONTRIBUTING

fe/example/src/data/candidates.ts, fe/example/src/data/faker.ts, fe/example/src/data/positions.ts, fe/example/src/data/qualifications.ts, fe/example/src/data/skills.ts, fe/example/src/data/users.ts, fe/package.json, yarn.lock
We're mocking up how Wingman could look like. It'll be easier to do this on the frontend only so we don't need to worry about data fetching and server-side pagination and all that jazz.
=> Add some frontend example data

.gitignore
Otherwise it will make this change locally whenever it runs
=> Update .gitignore for sku

fe/.gitignore, fe/lib/components/Example/Example.stories.tsx, fe/lib/components/JobCategorySelect/JobCategoriesSelect.stories.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.stories.tsx, fe/lib/components/LocationSuggest/LocationSuggest.stories.tsx, fe/lib/components/QuestionnaireBuilder/app.stories.tsx, fe/lib/components/QuestionnaireBuilder/components/GraphqlQueryRenderer/GraphqlQueryRenderer.stories.tsx, fe/sku.config.js
All the Wingman goodies are still on a branch so this is fairly unnoticeable. The blue is nice though.
=> Switch to APAC theme

fe/example/src/components/Breadcrumbs.tsx, fe/example/src/components/RelativeDate.tsx, fe/example/src/components/RichDropdown.treat.ts, fe/example/src/components/RichDropdown.tsx, fe/example/src/components/SearchField.tsx, fe/example/src/hooks/url.ts, fe/example/src/utils/text.ts, fe/package.json, yarn.lock
A few building blocks that are used across the example site.
=> Add bits and bobs

fe/example/src/App/Router.tsx, fe/example/src/pages/Positions/New.tsx, fe/example/src/widgets/AdProductSelect.treat.ts, fe/example/src/widgets/AdProductSelect.tsx, fe/example/src/widgets/BrandingSelect.treat.ts, fe/example/src/widgets/BrandingSelect.tsx, fe/example/src/widgets/NewAdForm.treat.ts, fe/example/src/widgets/NewAdForm.tsx, fe/example/src/widgets/NewPositionForm.tsx, fe/example/src/widgets/QuestionnaireSelect.tsx
This is super janky, but IE should be much better equipped to build a 9-star solution over this than I.
=> Add new position page

fe/example/src/App/Router.tsx, fe/example/src/pages/Ads/List.treat.ts, fe/example/src/pages/Ads/List.tsx, fe/example/src/pages/Positions/Detail.tsx, fe/example/src/pages/Positions/List.tsx
The filter fields don't do anything, though they would be neat to implement.
=> Add position list and detail pages

fe/example/src/App/Router.tsx, fe/example/src/pages/Positions/Brandings.tsx, fe/example/src/pages/Positions/Questionnaires.tsx
These should eventually become proper list views with edits, deletes and all that jazz.
They currently reuse the widgets that are embedded in the posting flow.
=> Add branding and questionnaire page stubs

fe/example/src/App/App.treat.ts, fe/example/src/App/App.tsx, fe/example/src/App/Sidebar.treat.ts, fe/example/src/App/Sidebar.tsx, fe/example/src/styles.ts
Using overflow containers for the main page content isn't great and can break general browser assumptions. A sticky sidebar is the secret sauce here.
=> Use normal page scrolling

fe/example/src/widgets/AdProductSelect.treat.ts, fe/example/src/widgets/AdProductSelect.tsx, fe/example/src/widgets/NewAdForm.tsx
Wingman is pretty poor in this regard, but small steps:
- Collapse ad products
- Collapse StandOut bullet points
=> Make the ad form more mobile-friendly

.eslintignore, .gitignore, .prettierignore, package.json, yarn.lock
This was lost in #188 due to `nohoist`.
=> Add concurrently dep

fe/example/src/App/App.tsx, fe/example/src/api/seekGraph.ts, fe/example/src/data/questionnaires.ts, fe/example/src/pages/Admin/Admin.test.tsx, fe/example/src/pages/Admin/Attachments.tsx, fe/example/src/pages/Positions/Questionnaires.tsx, fe/sku.config.js
This doesn't work with consumer-controlled compilation.
https://seek-oss.github.io/sku/#/./docs/configuration?id=rootresolution
=> Disable root resolution

.changeset/rare-walls-turn.md, fe/example/src/App/App.tsx, fe/example/src/pages/Admin/Attachments.tsx, fe/example/src/widgets/AdProductSelect.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx, fe/lib/components/Questionnaire/QuestionnaireForm/components/SingleSelect.tsx, fe/lib/components/Questionnaire/components/GraphqlQueryRenderer/GraphqlQueryRenderer.tsx
=> Migrate to RadioGroup

.changeset/wild-cougars-repair.md, fe/lib/components/Person/SpecifiedPersonForm.tsx
Issues with nested forms made this really hard to consume, if this component was even working properly.
=> Remove userForm hook from SpecifiedPersonForm

.changeset/blue-ads-shop.md, .changeset/eleven-drinks-listen.md, .changeset/orange-birds-perform.md, fe/example/src/pages/Ads/List.tsx, fe/example/src/widgets/NewPositionForm.tsx, fe/lib/components/LocationSuggest/LocationSuggestInput.tsx, fe/lib/components/Questionnaire/QuestionnaireBuilder/FormBuilder/components/NewPrivacyConsentForm/NewPrivacyConsentForm.tsx, fe/lib/components/Questionnaire/QuestionnaireBuilder/FormBuilder/components/NewQuestionForm/NewQuestionForm.tsx, fe/package.json
https://github.com/seek-oss/braid-design-system/releases/tag/v29.26.0
=> Use new Braid button variants

.changeset/orange-fishes-end.md, .gitignore, fe/lib/components/Questionnaire/QuestionnaireBuilder/FormBuilder/components/NewPrivacyConsentForm/NewPrivacyConsentForm.tsx, fe/package.json, yarn.lock
=> Banish yup and friends

.changeset/gentle-dogs-count.md, fe/lib/types/seek.graphql.ts, fe/lib/types/seekFragmentTypes.ts, fe/lib/types/seekSchema.graphql
Ryanair seems upset when upgrading the schema as this still has an outdated schema which doesn't have the breaking change to SpecifiedPerson & SpecifiedPersonInput
=> Update schema codegen

fe/lib/components/JobCategorySelect/README.md, fe/lib/components/JobCategorySuggest/README.md, fe/lib/components/LocationSuggest/README.md
`register` didn't work out too well for us.
=> Recommend react-hook-form Controller

.changeset/chilly-chicken-decide.md, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx, fe/lib/components/Questionnaire/QuestionnaireBuilder/FormBuilder/components/NewQuestionForm/NewQuestionForm.tsx
We don't need to beg users to fill in fields.
=> Shorten form placeholders

.changeset/angry-rats-invite.md, .changeset/cool-donkeys-brake.md, .changeset/selfish-grapes-tie.md, .changeset/silly-ladybugs-cough.md, fe/lib/components/Example/README.md, fe/lib/components/JobCategorySelect/JobCategoriesSelect.stories.tsx, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.stories.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/LocationSuggest/LocationSuggest.stories.tsx, fe/lib/components/LocationSuggest/LocationSuggest.tsx, fe/lib/components/LocationSuggest/LocationSuggestInput.tsx
See changesets for details.
---
Here's a particularly egregious issue that's been fixed:
=> Tweak alignment and spacing

.changeset/silly-ways-compete.md, fe/lib/components/Questionnaire/QuestionnaireForm/components/PrivacyConsent.tsx
This is now live on the SEEK apply form!
---
=> Render custom privacy consent prompt

fe/example/src/data/ads.ts, fe/example/src/data/brandings.ts, fe/example/src/data/candidates.ts, fe/example/src/data/positions.ts, fe/example/src/data/questionnaires.ts, fe/example/src/data/users.ts
This avoids spamming the console during tests
=> Fix deprecated faker usages

.changeset/clean-chefs-brake.md, .changeset/great-numbers-nail.md, fe/lib/components/Questionnaire/QuestionnaireBuilder/FormBuilder/components/NewQuestionForm/components/DisplayOption.tsx, fe/package.json
https://seek-oss.github.io/braid-design-system/components/Checkbox/#standalone
=> Improve accessibility of preferred option checkbox

.changeset/prefill-location-suggest.md, fe/lib/components/LocationSuggest/LocationSuggest.stories.tsx, fe/lib/components/LocationSuggest/LocationSuggest.tsx, fe/lib/components/LocationSuggest/LocationSuggestInput.tsx, fe/lib/components/LocationSuggest/README.md
This PR is triggered by the piece of work to make editing better in RyanAir. 
We need the Location Suggest component to load the initial value.
=> Initial location with pre-filled value

fe/lib/components/Example/Example.stories.tsx, fe/lib/components/JobCategorySelect/JobCategorySelect.stories.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.stories.tsx, fe/lib/components/LocationSuggest/LocationSuggest.stories.tsx, fe/lib/components/Person/SpecifiedPersonForm.stories.tsx, fe/lib/components/Questionnaire/app.stories.tsx, fe/lib/components/Questionnaire/components/GraphqlQueryRenderer/GraphqlQueryRenderer.stories.tsx
https://github.com/storybookjs/storybook/blob/master/MIGRATION.md#can-no-longer-add-decoratorsparameters-after-stories
=> Add Storybook decorators first

.changeset/fair-carrots-behave.md, fe/lib/components/Questionnaire/QuestionnaireForm/components/componentId.test.ts, fe/lib/components/Questionnaire/QuestionnaireForm/components/componentId.ts
This caused the questionnaire builder to WSoD when creating a new question under a Webpack 5 environment like sku 11.
=> Drop requirement for Node.js `Buffer` polyfill

.changeset/four-parrots-sneeze.md, .changeset/funny-candles-deliver.md, .changeset/good-spies-hug.md, .changeset/red-hats-smash.md, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx, fe/lib/components/LocationSuggest/LocationSuggestInput.tsx, fe/lib/components/Person/index.ts, fe/lib/components/Questionnaire/QuestionnaireBuilder/FormBuilder/components/NewPrivacyConsentForm/NewPrivacyConsentForm.tsx, fe/lib/components/Questionnaire/QuestionnaireBuilder/FormBuilder/components/NewQuestionForm/NewQuestionForm.tsx, fe/lib/components/Questionnaire/QuestionnaireBuilder/QuestionnaireBuilder.tsx, fe/lib/components/index.ts
I discovered how bad these were by playing around with viewports in Storybook.
=> Improve mobile responsiveness

fe/lib/components/Person/SpecifiedPersonForm.stories.tsx
https://storybook.js.org/docs/react/essentials/actions
---
=> Use Storybook actions

.changeset/clever-pillows-laugh.md, .changeset/pink-plums-hammer.md, fe/lib/components/JobCategorySelect/JobCategorySelect.mock.tsx, fe/lib/components/JobCategorySelect/JobCategorySelect.stories.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.mock.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.stories.tsx, fe/lib/components/LocationSuggest/LocationSuggest.mock.tsx, fe/lib/components/LocationSuggest/LocationSuggest.stories.tsx, fe/lib/private/MockComponentActions/MockComponentActions.tsx, fe/lib/storybook/controls.tsx
=> Add `Mock.showStorybookAction` prop

.changeset/small-socks-flow.md, fe/package.json, yarn.lock
It's upsetting that our 1.x release has been immediately superseded.
=> Pull in Scoobie border radii changes

.changeset/gold-tools-divide.md, .changeset/late-clocks-watch.md, .changeset/mighty-peaches-promise.md, .changeset/plenty-bulldogs-add.md, .changeset/tricky-dancers-rest.md, fe/lib/components/QuestionnaireBuilder/FormBuilder/FormBuilder.tsx, fe/lib/components/QuestionnaireBuilder/FormBuilder/components/NewPrivacyConsentForm/NewPrivacyConsentForm.tsx, fe/lib/components/QuestionnaireBuilder/FormBuilder/components/NewQuestionForm/NewQuestionForm.tsx, fe/lib/components/QuestionnaireBuilder/FormBuilder/components/PrivacyConsentEntry.tsx, fe/lib/components/QuestionnaireBuilder/FormBuilder/components/QuestionListEntry.tsx, fe/lib/components/QuestionnaireBuilder/QuestionnaireBuilder.stories.tsx, fe/lib/components/QuestionnaireBuilder/QuestionnaireBuilder.tsx, fe/lib/components/QuestionnaireForm/QuestionnaireForm.tsx, fe/lib/components/QuestionnaireForm/components/FreeText.tsx, fe/lib/components/QuestionnaireForm/components/MultiSelect.tsx, fe/lib/components/QuestionnaireForm/components/PrivacyConsent.tsx, fe/lib/components/QuestionnaireForm/components/SingleSelect.tsx, fe/lib/components/QuestionnaireQueryOutput/QuestionnaireQueryOutput.tsx
This was motivated by excess Card padding when we placed the QuestionnaireBuilder inside a Dialog as part of our new inlined posting flow. There were a few niggles that have built up over time that I was keen to address here.
=> Uplift QuestionnaireBuilder

.changeset/proud-rockets-happen.md, be/src/seekGraph/middleware.ts, be/src/seekGraph/schema.ts
=> Properly pipe through `seekApiUrlOverride`

fe/lib/components/BrandSelect/BrandSelect.mock.tsx, fe/lib/components/BrandSelect/BrandSelect.stories.tsx, fe/lib/components/BrandSelect/BrandSelect.tsx, fe/lib/components/BrandSelect/__fixtures__/brands.ts, fe/lib/utils/createCursorConnection.ts
Per https://github.com/seek-oss/wingman/pull/575#discussion_r706994375.
=> Make brand pagination fully dynamic

.changeset/thin-emus-add.md, fe/lib/components/BrandSelect/styles.css.ts
=> Avoid FOUC when loading images in Firefox

.changeset/red-ducks-flow.md, fe/lib/components/BrandSelect/BrandSelect.tsx, fe/lib/components/BrandSelect/BrandTile.tsx, fe/lib/components/BrandSelect/BrandTiles.tsx, fe/lib/components/BrandSelect/PaginatedBrands.tsx, fe/lib/components/BrandSelect/README.md
Update props to BrandSelect component:
* Change `onSelect` to optional
* Add `onBrandingQueryResponse` callback to return SEEK API Response
* Add `showCopyableOid` flag
=> Update BrandSelect props

.changeset/cool-maps-yell.md, fe/lib/components/LocationSuggest/LocationSuggestInput.tsx
Update location detect button copy
https://trello.com/c/zCPnzVCX/44-align-location-suggest-button-copy
=> Location detect button copy

.changeset/tender-pans-swim.md, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
Auto-select the first option if there is no initial value and the confidence is greater than 0.5
=> Category suggestion auto-select

.changeset/changelog.js, .changeset/config.json, .changeset/tender-pans-swim.md, package.json, yarn.lock
This is like the Changesets `changelog-github` package, but it produces terser changelogs and automatically bolds commit title scopes.
Copied across from https://github.com/seek-oss/skuba.
=> Use custom GitHub changelog generator

.changeset/clean-fans-fix.md, fe/lib/components/SalaryDetails/SalaryDetails.tsx, fe/lib/components/SalaryDetails/validateSalary.ts
Reference to https://github.com/seek-oss/wingman/pull/611#discussion_r718129839
=> Add character limit to salary description

.changeset/grumpy-ears-draw.md, fe/lib/components/SpecifiedPersonForm/SpecifiedPersonForm.tsx
=> Wrap "Add contact" button in `Actions`

.changeset/tasty-trainers-admire.md, fe/lib/components/SalaryDetails/SalaryDetails.stories.tsx
This matches the other top-level groups
=> Uncamelcase "salary details" Storybook group

.changeset/kind-moose-relax.md, fe/lib/components/SalaryDetails/SalaryDetails.tsx
=> Update wording for salary details pay range

.changeset/honest-keys-know.md, fe/lib/components/SpecifiedPersonForm/SpecifiedPersonForm.mock.tsx, fe/lib/components/SpecifiedPersonForm/SpecifiedPersonForm.stories.tsx, fe/lib/components/SpecifiedPersonForm/SpecifiedPersonForm.tsx, fe/lib/index.ts
Although `SpecifiedPersonForm` doesn't require GraphQL mocking, this does add our Storybook & GitHub button links.
=> Add `MockSpecifiedPersonForm`

.changeset/early-planets-rule.md, fe/lib/components/QuestionnaireForm/components/SingleSelect.tsx
=> Make single select a dropdown at >5 choices

.changeset/purple-oranges-repair.md, .github/renovate.json5, be/package.json, fe/lib/types/apolloHelpers.ts, fe/lib/types/seekApi.graphql.ts, fe/lib/types/seekApi.typeDefs.ts, fe/package.json, package.json, yarn.lock
https://github.com/graphql/graphql-js/releases/tag/v16.0.0
=> Upgrade to GraphQL 16

.changeset/perfect-carpets-walk.md, fe/lib/components/LocationSuggest/LocationSuggest.mock.tsx
As reported via a partner research session
=> Fix GitHub source path for location suggest

.github/workflows/release.yml
This was already documented in CONTRIBUTING but wasn't wired up in CI.
---
Canary here: https://github.com/seek-oss/wingman/actions/runs/1913580319
=> Support beta releases

.github/workflows/release.yml
Per annotated warning here:
https://github.com/seek-oss/wingman/actions/runs/1913580319
=> Pin `changesets/action@v1`

.changeset/moody-apricots-fold.md, fe/lib/components/BrandSelect/BrandSelect.stories.tsx, fe/lib/components/BrandSelect/BrandSelect.tsx
As discussed with product. This will be especially nice if/when we prioritise the default brand in the response.
=> Preselect the first brand

.github/workflows/release.yml
This should allow CI to run on Changesets PRs.
=> Use `seek-oss-ci` token for release

.github/workflows/codeql-analysis.yml, .github/workflows/release.yml, .github/workflows/validate.yml, be/package.json, fe/package.json, package.json
- Fix CodeQL branch warning
- Lock down permissions
- Pin action versions
- Remove unnecessary LFS support
=> Uplift workflows

be/tsconfig.json
=> Exclude DOM type definitions

.changeset/purple-stingrays-cough.md, fe/lib/components/BrandSelect/BrandSelect.tsx
This aligns with e.g. `JobCategorySelect`.
=> BrandSelect: Support `hideLabel` property

README.md
- Fix link for ad selection
- Add link for questionnaires
=> Update panel links

.changeset/little-needles-train.md, .changeset/shaggy-carrots-yell.md, fe/lib/components/JobCategoryLookup/README.md, fe/lib/components/LocationLookup/LocationLookup.mock.tsx, fe/lib/components/LocationLookup/LocationLookup.stories.tsx, fe/lib/components/LocationLookup/LocationLookup.tsx, fe/lib/components/LocationLookup/README.md, fe/lib/components/LocationLookup/__fixtures__/location.ts, fe/lib/components/LocationLookup/index.ts, fe/lib/index.ts, fe/lib/types/seekApi.graphql.ts, fe/lib/types/seekApi.typeDefs.ts
=> Add LocationLookup component

.changeset/young-bees-smoke.md, fe/lib/components/BreadCrumbsString/BreadCrumbsString.tsx, fe/lib/components/JobCategoryLookup/JobCategoryLookup.tsx, fe/lib/components/LocationLookup/LocationLookup.tsx, fe/lib/components/LocationSuggest/LocationSuggest.tsx
=> Fix incorrect ordering of breadcrumbs

.changeset/real-kangaroos-type.md
=> Add changeset for uuid@9

.changeset/famous-flies-argue.md, fe/lib/private/CopyableOid.tsx, fe/package.json, yarn.lock
https://github.com/seek-oss/scoobie/releases/tag/v14.0.0
=> Upgrade to Scoobie 14

.changeset/tame-cycles-leave.md, fe/lib/components/JobCategorySelect/JobCategorySelect.stories.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.stories.tsx, fe/lib/components/LocationSuggest/LocationSuggest.stories.tsx, fe/lib/components/QuestionnaireBuilder/FormBuilder/components/NewPrivacyConsentForm/NewPrivacyConsentForm.tsx, fe/lib/components/QuestionnaireBuilder/FormBuilder/components/NewQuestionForm/NewQuestionForm.tsx, fe/lib/components/QuestionnaireBuilder/FormBuilder/components/NewQuestionForm/components/SelectOptions.tsx
https://myseek.atlassian.net/wiki/spaces/DSYS/pages/2068648985/Error+states#Content-guidelines
=> Align validation messages with recommendations

.changeset/silver-laws-listen.md, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySelect/queries.ts, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx, fe/lib/types/apolloHelpers.ts, fe/lib/types/seekApi.graphql.ts, fe/lib/types/seekApi.typeDefs.ts, yarn.lock
Update the input based on this relevant market categories change.
https://developer.seek.com/schema/#/query/jobCategories
=> Add positionLocation input to jobCategories query

.changeset/quick-onions-remember.md, fe/lib/components/LocationSuggest/LocationSuggest.tsx
This was getting passed as a prop but never called when the autosuggest was cleared
=> Call onClear in LocationSuggest

.changeset/thirty-houses-smoke.md, fe/lib/components/LocationSelectMap/queries.ts, fe/lib/components/LocationSuggest/queries.ts, fe/lib/types/apolloHelpers.ts, fe/lib/types/seekApi.graphql.ts, fe/lib/types/seekApi.typeDefs.ts
This pulls in the associated `currency` for our location components.
=> Extract `currencies` from location and run codegen

.changeset/six-ravens-flash.md, fe/lib/components/SalaryDetails/README.md, fe/lib/components/SalaryDetails/SalaryDetails.mock.tsx, fe/lib/components/SalaryDetails/SalaryDetails.stories.tsx, fe/lib/components/SalaryDetails/SalaryDetails.tsx, fe/lib/components/SalaryDetails/fixtures/currencies.ts, fe/lib/components/SalaryDetails/fixtures/payTypes.ts, fe/lib/components/SalaryDetails/queries.ts, fe/lib/components/SalaryDetails/types.ts, fe/lib/index.ts, fe/lib/types/seekApi.graphql.ts
This is in reference to https://github.com/SEEK-Jobs/indie-ryanair-frontend/pull/883#pullrequestreview-1513491646 and implements the queries in https://github.com/SEEK-Jobs/indie-graphql-server/pull/2249.
=> Update `SalaryDetails` to query currencies and pay types

.changeset/thin-elephants-boil.md, be/src/seekGraph/middleware.ts
This was causing some type errors when implementing the upgrade.
=> Add generics in createSeekGraphMiddleware

.changeset/tall-papayas-sort.md, .eslintignore, .prettierignore, fe/package.json, yarn.lock
Should help when skipLibCheck isn't off.
=> Move @types/autosuggest-highlight to dependencies

.github/workflows/snapshot.yml, .github/workflows/validate.yml, CONTRIBUTING.md, fe/package.json
Stealing these from seek-oss/skuba.
=> Enable provenance & snapshots

.changeset/tender-grapes-add.md, fe/lib/components/BrandSelect/BrandSelect.tsx, fe/lib/components/JobCategoryLookup/JobCategoryLookup.tsx, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx, fe/lib/components/LocationLookup/LocationLookup.tsx, fe/lib/components/LocationSelectMap/LocationSelectMap.tsx, fe/lib/components/LocationSuggest/LocationSuggest.tsx, fe/lib/components/LocationSuggest/LocationSuggestInput.tsx, fe/lib/components/SalaryDetails/SalaryDetails.tsx
useEffect considered harmful
Also removed a couple simple re-renders 🐿️
=> Support passing `context` into components

.changeset/dry-suns-swim.md, fe/lib/components/BrandSelect/BrandTile.tsx, fe/lib/components/BrandSelect/styles.css.ts, fe/lib/components/LocationSelectMap/styles.css.ts, fe/lib/utils/colorMode.ts, fe/package.json, pnpm-lock.yaml
=> Add experimental support for color modes

fe/.storybook/main.ts, fe/package.json, pnpm-lock.yaml
Forgot to remove this in https://github.com/seek-oss/wingman/pull/1284
=> Fix storybook

.changeset/poor-steaks-shop.md, fe/lib/components/QuestionnaireBuilder/FormBuilder/state/formBuilderState.ts, fe/package.json, pnpm-lock.yaml
=> Revert "Revert "fix: @types/uuid""
