be/.eslintrc.js, be/README.md, be/package.json, be/server/src/app.ts, be/src/index.ts, be/src/seekGraph/constants.ts, be/src/seekGraph/context.test.ts, be/src/seekGraph/context.ts, be/src/seekGraph/middleware.test.ts, be/src/seekGraph/middleware.ts, be/src/seekGraph/schema.ts, be/src/seekGraph/types.ts, be/src/testing/graphql.ts, be/tsconfig.json, yarn.lock
This is the first cab off the rank as it doesn’t depend on external infrastructure. It’s slightly restructured from our first cut at this functionality:
- Auth exchange is handled by a central `getPartnerToken` function instead of being bolted on as a separate middleware on the same path
- A `graphql-tools` executor replaces Apollo links
- A middleware is returned, which seems nicer than `applyMiddleware`
=> Add createSeekGraphMiddleware

be/README.md, be/src/getPartnerToken.ts, be/src/index.ts, be/src/seekAttachment/headers.test.ts, be/src/seekAttachment/headers.ts, be/src/seekAttachment/middleware.test.ts, be/src/seekAttachment/middleware.ts, be/src/seekAttachment/types.ts, be/src/seekGraph/context.ts, be/src/seekGraph/middleware.test.ts, be/src/seekGraph/schema.ts, be/src/seekGraph/types.ts, be/src/testing/mock.ts
This configures a proxy handler for attachment downloads. The major difference compared to the original implementation is that this has been rebased on `node-fetch` and passes a readable stream through to Koa.
I’ve tried to reuse the same `GetPartnerToken` definition here but I think the cracks are starting to show. Once the middlewares have settled a little, we can revisit its signature.
=> Add createSeekAttachmentMiddleware

fe/sku.config.js
No, I’m not going to type everything as JSX.Element.
=> Ignore explicit-module-boundary-types on frontend

be/README.md, be/example/src/api/attachment.ts, be/example/src/api/cors.ts, be/example/src/api/index.ts, be/example/src/api/webhook.ts, be/example/src/config.ts, be/package.json, be/src/index.ts, be/src/partnerWebhook/middleware.test.ts, be/src/partnerWebhook/middleware.ts, be/src/partnerWebhook/signature.ts, be/src/partnerWebhook/types.ts, be/src/testing/data.ts, be/src/testing/mock.ts, fe/example/src/App/HomePage.tsx, fe/example/src/App/Webhook.tsx, fe/example/src/api/partnerWebhook.ts, yarn.lock
This only formally covers input validation and signature verification, though storage could be implemented through the callback.
It also wires up the example frontend and backend with a new feature: the frontend can POST a fake webhook. If we can’t figure out a nice way to get the webhook interaction working in a self-contained manner, we may just support some form of seeding. This could be triggered at startup and/or by user interaction.
---
=> Add createPartnerWebhookMiddleware stub

.github/workflows/release.yml, package.json
Because `yarn version` prints the literal Yarn version 🤡
=> Fix version command, again

.changeset/tender-dolphins-knock.md, be/README.md, be/package.json, be/src/browserToken/middleware.test.ts, be/src/browserToken/middleware.ts, be/src/browserToken/types.ts, be/src/constants.ts, be/src/index.ts, be/src/testing/koa.ts, be/src/testing/tokens.ts, yarn.lock
This is better practice than using the SeekGraph proxy as the access is scoped to a hirer, as it would be in an actual third-party system. The interface is a bit rough but hopefully the core functionality is there; I'll follow this up with an actual implementation in the example frontend.
=> Add createBrowserTokenMiddleware

.changeset/eight-phones-camp.md, codegen.yml, fe/lib/types/seekFragmentTypes.ts, fe/lib/types/seekTypes.ts, package.json, types/seek.graphql.ts, types/seekFragmentTypes.ts, yarn.lock
- Adds SEEK graphql type via codegen. This is pulled into the root of wingman to then be consumed by both the frontend and backend.
- Re-exports these within the front-end so it and consumers of `fe/lib` can use them. Keen to get some feedback on this, it means we have a  double up in files but easier to maintain/use.
As they are being re-exported in `/fe/lib/types` we can consume them like
```
import { JobCategory } from 'lib/types/seekTypes';
interface Props {
jobCategory: JobCategory;
}
```
=> feat: Add SEEK graphql types

.changeset/dirty-items-wave.md, be/package.json, be/src/seekGraph/middleware.ts, yarn.lock
There was a bug in Apollo Server that allowed introspection through subscriptions, bypassing validation checks.
The SEEK API schema is publicly available so it doesn't impact us, but we don't make use of subscriptions anyway.
https://github.com/apollographql/apollo-server/security/advisories/GHSA-w42g-7vfc-xf37
=> Disable Apollo Server subscriptions

.changeset/itchy-roses-grab.md, be/src/browserToken/middleware.test.ts, be/src/browserToken/middleware.ts, be/src/browserToken/types.ts, be/src/constants.ts, be/src/partnerWebhook/middleware.ts, be/src/seekAttachment/middleware.ts
The middleware now points to the browser token playground URL, and accepts a `callback` for debugging/logging.
=> Apply fixes to browser token middleware

.changeset/three-jars-collect.md, fe/lib/components/LocationSuggest/LocationSuggest.tsx
The typing on the passed in ApolloClient is more restrictive than it needs to be for consumers. Removes the Record or string and unknown to just unknown.
=> refactor: removes enforced/restrictive typing on ApolloClient

.changeset/heavy-eggs-flow.md, fe/lib/components/LocationSuggest/LocationSuggest.tsx, fe/lib/components/LocationSuggest/LocationSuggestInput.tsx
As we are not compiling wingman (yet), the consumer needs to set-up custom resolve rules for `/lib`. Switches to relative paths for SEEK type imports.
=> refactor(LocationSuggest): switch to relative path to resolve SEEK types

.changeset/quick-carpets-attend.md, be/src/browserToken/middleware.test.ts, be/src/browserToken/middleware.ts, be/src/constants.ts
The same URL can now be used across Playground and live.
Remove references to the old Playground-specific URL which wasn't intended for external use.
=> Unify browser token URLs

fe/lib/components/Example/Example.stories.tsx, fe/lib/components/QuestionnaireBuilder/app.stories.tsx, fe/lib/components/QuestionnaireBuilder/components/GraphqlQueryRenderer/GraphqlQueryRenderer.stories.tsx
Cleaning up the other themes and making them all the same. I noticed a bug when switching between stories of different themes it would not load the CSS, this only happened in the built version of storybook (not dev).
In addition, eventually I would like to eventually make the required wrapping `BraidLoadableProvider` a util we can include or add to all stories via global config.
=> refactor: change all storybook braid themes to unified

.changeset/lemon-worms-flow.md, fe/lib/components/JobCategorySelect/JobCategoriesSelect.stories.tsx, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx, fe/lib/components/JobCategorySelect/README.md, fe/lib/components/JobCategorySelect/__fixtures__/jobCategories.ts, fe/lib/components/JobCategorySelect/index.ts, fe/lib/components/JobCategorySelect/queries.ts, fe/lib/components/index.ts, fe/lib/utils/findCategory.ts, fe/lib/utils/index.ts
Pulls in the JobCategorySelect. The JobCategory select component provides a full list of parent and child job categories for SEEK. Returns a JobCategory (parent or child) with object identifier on category select.
This component can be used to fetch a job category or used inline within a form that generates the input structure for other queries and mutations. For example, you can use this component to resolve a job category OID for PositionPosting.
- Storybook example, only resolves a mock query with 2 job categories and 2 child job categories each
- Readme with usage instructions.
=> feat: add JobCategorySelect component

.changeset/late-chicken-compete.md, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
As we are not compiling our packages we cannot resolve `lib/xxx`. Switches import paths to relative to fix import error within consumers.
=> fix(JobCategorySuggest): module resolution

.changeset/twelve-lamps-cover.md, fe/lib/components/JobCategorySuggest/JobCategorySuggest.stories.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
When using JobCategorySuggest as a field in a form you could not pass through props to the underlying fields
- Removes hardcoded "name" prop on radio
- Creates a new field message to receive passed in "message" and "tone" 
- Pass tone, and spreads extra props (name and other field props) to the radio button
=> Fix(JobCategorySuggest): field props not being passed through correctly 

.changeset/seven-monkeys-retire.md, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
- Sets `tone` on `JobCategorySuggestChoices.tsx ` as optional
- Sets `message` on main parent component `JobCategorySuggest.tsx` as optional
=> fix(jobCategorySuggest): Make `tone` and `message` props optional

.changeset/rotten-walls-sit.md, fe/lib/components/QuestionnaireBuilder/components/GraphqlQueryRenderer/GraphqlQueryRenderer.tsx
Right now we produce JSON with top-level `variables` and `valid` properties.  If you copy and paste this in to the Playground it will fail; you just need the variables.
This doesn't bother with `valid` as it doesn't seem to be possible to create an invalid questionnaire with the UI.
=> Fix questionnaire builder mutation variables

fe/lib/components/QuestionnaireBuilder/QuestionnaireBuilder/FormBuilder/components/NewPrivacyConsentForm/NewPrivacyConsentForm.tsx, fe/package.json, yarn.lock
- Built-in Yup support has been removed in favour of a `@hookform/resolvers` package that supports multiple schema validators.
This just passes our existing Yup schema in to the new resolver.
- `react-hook-form` is moving away from `as` for non-trivial cases (see react-hook-form/react-hook-form#1580).
Their types no longer include `onChange` for the `as` prop even though they're passing it. This works for most form elements but Braid requires `TextField`s to have an `onChange`.
This seems to technically be a `react-hook-form` type bug but they seem to be pushing people towards the `render` prop anyway. I think the result also more clearly separates the form logic from the Braid logic.
=> Update to react-hook-form@6

fe/example/src/components/Table/Table.treat.ts, fe/example/src/components/Table/Table.tsx, fe/example/src/components/Table/TableCell.tsx, fe/example/src/components/Table/TableCellLink.treat.ts, fe/example/src/components/Table/TableCellLink.tsx, fe/example/src/components/Table/index.ts
This kicks off the deconstruction of the `mock-frontend` mega-branch. I'll try to keep things small so they are easier to review in isolation.
This is all going into the `fe/example` directory as I'm not sure if any of this stuff should be part of our package interface. We can always shift stuff over once we've evaluated that they are a good fit with non-mock data.
=> Add example Table component

.github/workflows/release.yml, .gitignore, fe/example/src/App/App.tsx, fe/example/src/App/Sidebar.tsx, fe/example/src/client.tsx, fe/example/src/render.tsx, fe/example/src/types.ts, fe/package.json, fe/sku.config.js, package.json, scripts/deploy, yarn.lock
This drops the Storybook deployer in favour of a simple script with plenty of hardcoding. This allows us to trivially customise the directory structure of the `gh-pages` branch and add in our mock site.
<https://seek-oss.github.io/wingman>
I initially thought of running a script after the Storybook deployer, but unfortunately it deletes its working directory after deployment.
=> Craft artisanal deployment

fe/example/src/components/ClientOnly.tsx
React yells in the console when the hydrated client output doesn't match the server render, and a mismatch can lead to weird rendering issues. Instead, we defer client-side changes to a follow-up render.
=> Fix rehydration issue with `ClientOnly`

.changeset/plenty-dolls-whisper.md, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
Right now if you use a JobCategorySuggest component and supply it an ID, due to type inheritance from Braids Radio component it will use that instead of the supplied job category ID. From our use cases, we don't actually need control over the ID as any external control/listening is done by the forwarded ref or the name attribute. 
- Omits the ID from the type of JobCategorySuggest 
- Re-orders props on Radio component to enforce the others are not overwritten.
=> Fix: JobCategorySuggest ID overwritten preventing label selection

.changeset/pretty-swans-dress.md, .changeset/tidy-birds-relax.md, codegen.yml, fe/lib/components/JobCategorySelect/JobCategoriesSelect.stories.tsx, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySelect/README.md, fe/lib/components/JobCategorySelect/__fixtures__/jobCategories.ts, fe/lib/components/JobCategorySelect/queries.ts, fe/lib/components/JobCategorySuggest/JobCategorySuggest.stories.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/README.md, fe/lib/components/JobCategorySuggest/__fixtures__/jobCategorySuggest.ts, fe/lib/components/JobCategorySuggest/queries.ts, fe/lib/components/LocationSuggest/LocationSuggest.stories.tsx, fe/lib/components/LocationSuggest/LocationSuggest.tsx, fe/lib/components/LocationSuggest/README.md, fe/lib/components/LocationSuggest/__fixtures__/locationSuggest.ts, fe/lib/components/LocationSuggest/__fixtures__/nearestLocations.ts, fe/lib/components/LocationSuggest/queries.ts, fe/lib/testing/ApolloMockProvider.tsx, fe/lib/testing/graphql.d.ts, fe/lib/types/seek.graphql.ts, fe/lib/types/seekSchema.graphql, fe/package.json, fe/sku.config.js, package.json, yarn.lock
For the most part, this is a mechanical conversion of import paths.
Interesting bits:
- `ssr` is now toggled off across all widgets, so they don't run on sku static renders in case their parent component is not excepted by some `ClientOnly` implementation.
- `mock-apollo-client` does not support Apollo Client 3, so we roll our own client mock by pulling down the SEEK API schema and serving it up via `makeExecutableSchema`.
=> Upgrade to Apollo Client 3

.changeset/twelve-kiwis-stare.md
The update to skuba 3.7.3 https://github.com/seek-oss/wingman/pull/75/ updated the main file reference from `"lib/index.ts"` to `"lib/index.js"` but was never released
=> chore: trigger a new release of wingman-be to update broken package.json main file link

.changeset/late-beans-dream.md, fe/lib/components/Questionnaire/components/FormBuilderQueryInput.tsx
Removes unnecessary layers of braid so the consuming app can have a better layout
=> Unnest graphQL input component

yarn.lock
https://snyk.io/vuln/SNYK-JS-PROPERTYEXPR-598800
=> Relock property-expr

.changeset/itchy-garlics-smash.md, fe/lib/components/Questionnaire/QuestionnaireForm/QuestionnaireForm.tsx, fe/lib/components/Questionnaire/QuestionnaireForm/components/PrivacyConsent.tsx
This aligns with how the consent is rendered on the candidate site, including ignoring `descriptionHtml`
=> Align Privacy Consent render with candidate

.changeset/thick-bugs-hide.md, fe/lib/components/Questionnaire/QuestionnaireBuilder/QuestionnaireBuilder.tsx, fe/lib/components/Questionnaire/app.stories.tsx, fe/lib/components/Questionnaire/components/GraphqlQueryRenderer/GraphqlQueryRenderer.tsx, fe/lib/components/Questionnaire/mapping.ts, fe/lib/components/Questionnaire/questionTypes.ts
This is currently broken unless a mutation is provided. Instead, this depends on our consumers supplying their own ID. This can either be provided from their session state or from an explicit input.
=> Remove hirer ID from the questionnaire builder

.changeset/forty-ads-love.md, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
With #239 we changed the radio group value to be index based, as a result we need to update the managed radio group with the selected index not the SEEK ID.
- This changes the current useState used for job category to be purely index (int) based and not store the JobCategory choice. Within the `onSelect` passed in function we still send back the full jobCategory to the parent.
=> fix: job category suggest

.changeset/late-kids-trade.md, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
Moves back to a SEEK ID for the value of radio group items:
Some form libraries such as [react-hook-form](https://react-hook-form.com/) use the value of the underlying radio button via a `ref` to get and set its form state. 
Switching it back to the ID of the JobCategory means we can use this value in parent components without a callback.
=> refactor(JobCategorySuggest): Switch to JobCategory ID for value of RadioItem

.changeset/famous-rats-rest.md
This was accidentally released under the backend package.
=> JobCategorySuggest: Use ID as RadioItem value

.changeset/slimy-seas-provide.md, fe/lib/components/Person/SpecifiedPersonForm.tsx
The consumers callback wasn't firing, but the parent form submission was 😓 
Uses https://github.com/react-hook-form/react-hook-form/issues/1005 
I'm on the fence as to whether this component should be refactored to just not use `useForm`
=> Fix SpecifiedPersonForm event handling

.changeset/ten-ants-complain.md, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
This was causing `react-hook-form` consumer usage to incorrectly choose the hardcoded `id` rather than the supplied `name` as the field name.
=> Forward JobCategorySuggest name properly

.github/workflows/validate.yml, fe/example/src/pages/Positions/Questionnaires.tsx, fe/lib/components/Questionnaire/index.ts
Some tooling change in `sku build` really hates the indirection of an export-only file. This removes those unused re-exports to reduce the chance of it happening again, and runs `sku build` on branches so we catch the issue earlier in future.
=> Fix frontend build

fe/lib/components/private/RedactableText/RedactableText.tsx
This is some internal mock code that doesn't require a release.
=> Remove redundant classnames usage

.changeset/nice-ghosts-move.md, fe/lib/components/Questionnaire/QuestionnaireBuilder/FormBuilder/components/NewPrivacyConsentForm/NewPrivacyConsentForm.tsx
An empty string `descriptionHtml` is a bit awkward.
=> Require privacy consent description field

.changeset/rare-hotels-destroy.md, codegen.yml, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySelect/queries.ts, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx, fe/lib/components/JobCategorySuggest/queries.ts, fe/lib/types/seek.graphql.ts, fe/lib/types/seekFragmentTypes.ts, fe/lib/types/seekSchema.graphql
- Use typed GraphQL operations
- Don't query our children's parent. This is unneeded and increases the complexity of our GraphQL operation
- Inline the `nestedJobCategoryAttributes` fragements only used in a single place
- Type our props to only include the fields we're selecting, not the entire infinite `JobCategory` object
=> Clean up job category GraphQL queries

fe/example/src/pages/Ads/List.tsx, fe/lib/components/private/RedactableText/RedactableText.tsx, yarn.lock
This is broken on classnames 2.3+, which can be pulled in via Renovate lock file maintenance.
https://github.com/JedWatson/classnames/issues/240
=> Avoid object-style classnaming

.changeset/smooth-rules-cry.md, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx, fe/lib/components/JobCategorySelect/queries.ts, fe/lib/types/seek.graphql.ts, fe/lib/types/seekFragmentTypes.ts, fe/lib/types/seekSchema.graphql, fe/lib/utils/findCategory.ts, fe/lib/utils/findObjectByOid.ts, fe/lib/utils/index.ts
The parent of a top-level job category will always be `null`. Selecting it is misleading and wastes bandwidth.
This also tightens up some internal types to better reflect the partial selection set.
=> Don't select `parent` in `jobCategories` query

.changeset/eleven-kiwis-burn.md, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx
Job posting in ANZ requires a child category for both pricing & posting.
Pass back the category node type (`parent` or `child`) so we can validate we have the right type of category. For example, we could block posting until the user has selected a `child`.
=> Provide job category node type

.changeset/purple-geese-notice.md, fe/lib/components/LocationSuggest/LocationSuggest.tsx
**Issue:** If the "Detect" location button doesn't work (e.g. user has blocked browser behaviour), then an error will appear. This error doesn't disappear on a successful location search, which can make it confusing during its usage.
Quick video showing fix:
https://user-images.githubusercontent.com/22812702/126429104-ed3e5f16-1c77-410e-8e81-5df2ef6db560.mov
=> Remove detect error messaging on successfully location query

.changeset/fresh-mirrors-impress.md, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.stories.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
**What is this change:**
This PR adds a `Other` option to the list of suggested job categories. 
**Why do we need this change:**
This is so RyanAir create flow follows UX recommendations and shows a full list of categories if the suggested list doesn't contain the category the hirer wants.
**Note:**
- We have added JobCategorySelect in the JobCategorySuggest component as suggested [here](https://github.com/seek-oss/wingman/pull/484#issuecomment-885247390).
Current UI:
=> Add Other option to job category choices

.changeset/poor-zoos-play.md, fe/lib/components/Questionnaire/QuestionnaireBuilder/QuestionnaireBuilder.tsx, fe/lib/components/Questionnaire/app.stories.tsx
This lets us hide our raw GraphQL output from the questionnaire builder.
This is useful for when the questionnaire builder is embedded in a job posting flow versus being used for developer documentation.
=> Make questionnaire builder's GraphQL dump optional

.changeset/small-garlics-join.md, fe/lib/components/JobCategorySelect/JobCategorySelect.stories.tsx, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
The inherited props from Braid 30.3 are a bit tricky because they use a union of possible label props. This component already has a `hideLabel` concept so it should be fine to require the plain `label` prop here.
=> Require `label` prop in JobCategorySelect

fe/lib/components/JobCategorySelect/JobCategorySelect.stories.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.stories.tsx, fe/lib/components/LocationSuggest/LocationSuggest.stories.tsx, fe/lib/components/Person/SpecifiedPersonForm.stories.tsx, fe/lib/components/Questionnaire/QuestionnaireBuilder.stories.tsx, fe/lib/components/Questionnaire/components/GraphqlQueryRenderer/GraphqlQueryRenderer.stories.tsx, fe/lib/storybook/controls.tsx, fe/lib/storybook/decorators.tsx, fe/package.json, fe/sku.config.js, yarn.lock
We can't place controls on decorators, so we instead propagate a `braidThemeName` arg through each story into the provider directly.
This should make it easier to use the Component Story Format files without requiring Storybook dependencies.
=> Drop Storybook knobs

.changeset/pink-eagles-exist.md, fe/lib/components/QuestionnaireBuilder/FormBuilder/FormBuilder.tsx
This should be the last of the churn for now. This looked overly noisy when the builder was rendered within a single card with a bunch of other dividers.
=> Remove divider between QuestionnaireBuilder components

.changeset/gold-grapes-fix.md, be/src/browserToken/middleware.ts, be/src/browserToken/types.ts, be/src/seekGraph/schema.ts, be/src/seekGraph/types.ts
This is to support resurrecting some of SEEK's internal staging environment. External consumers should be able to ignore this.
=> Support overriding SEEK API URLs

.changeset/lucky-moons-return.md, .changeset/tidy-plants-speak.md, fe/lib/components/AdSelectionFallback/AdSelectionFallback.mock.tsx, fe/lib/components/AdSelectionFallback/AdSelectionFallback.stories.tsx, fe/lib/components/AdSelectionFallback/AdSelectionFallback.tsx, fe/lib/index.ts
This is a simple Storybook action wrapper around the AdSelectionFallback component. There's nothing particularly exciting to see in Storybook, but it was easy enough to include this for alignment with other widgets.
=> Add MockAdSelectionFallback

.changeset/smooth-starfishes-smash.md, fe/lib/components/QuestionnaireQueryInput/QuestionnaireQueryInput.tsx
This was caught by TypeScript 4.4. It looks like we're expecting a `ValidationError` from our internal `indie-api-types` library which has `key` property. However, we're actually receiving a Runtypes `ValidationError` which results in this zen message:
> ValidationError: undefined is invalid
This just dumps the full Runtypes validation error as part of the normal Error handling.
=> Fix rendering GraphQL query input validation error

.changeset/shiny-pillows-lay.md, fe/package.json
Having multiple copies of `graphql` can cause unexpected behaviour. Trying to add this as a dependency to an existing internal repo caused GraphQL codegen to fail due to duplicate instances.
We already have `graphql` as a dev dependency on the top level we can use for our tests.
=> Move `graphql` to a peer dependency

.changeset/early-phones-remember.md, fe/lib/components/LocationSuggest/LocationSuggest.tsx
In two cases the `client` in non-null. In the third case we're using `client.query` which doesn't accept a `client` property.
=> Remove no-op client spreads

.changeset/famous-boats-cheat.md, fe/lib/types/apolloTypePolicies.ts
These aren't available from normal pagination queries but can be queried directly from a browser.
=> Add Apollo type policy for ontologies

.changeset/late-dancers-cross.md, fe/lib/types/apolloTypePolicies.ts
This is based on a review of objects that have an queryable primary object identifier. I was avoiding parts of the schema only accessible with a partner token but Apollo client can also be used server-to-server.
=> Add additional Apollo type policies

.changeset/poor-eggs-dress.md, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/LocationSuggest/LocationSuggest.tsx
Remove `fetchPolicy: 'no-cache`' from all queries except for our realtime suggest queries. By default Apollo doesn't limit its cache size so we could slowly leak memory with repeated suggestions.
=> Rationalise fetch policies

.changeset/nine-beans-camp.md, fe/lib/components/ApolloMockProvider/ApolloMockProvider.tsx, fe/lib/types/apolloTypePolicies.ts
Our Apollo type policy was imported from an internal repository that consistently uses infinitely scrolled lists to display paginated data. However, this makes a number of assumptions about how the data is used:
1. It assumes that the data should be flipped in reverse pagination so the oldest data appears first. When paginating forwards and backwards using a fixed page size this causes the data to flip when paginating backwards which is unexpected.
2. It expects data to always be appended in the same direction which isn't true for page-based pagination.
This turns `apolloTypePolicies` in to a function that now takes a `paginationPolicy` property. By default this is `conservative` which behaves the same way raw GraphQL queries would. This can be changed to `infinite-scroll` to opt-in to …
=> Disable infinite scrolling opinions by default

.changeset/clever-bottles-return.md, fe/lib/private/questionnaires/types.ts
In the SEEK API `ApplicationQuestionChoiceInput.value` is non-null while `ApplicationQuestionChoice.value` is nullable.
Our choice input Runtype had this as nullable which is incorrect. This was found via type errors in an internal repository.
=> Make question choice input value non-null

.github/renovate.json5
=> Ignore `node-fetch` Renovates

fe/example/src/App/Router.tsx, fe/example/src/App/Sidebar.tsx, fe/example/src/hooks/user.tsx, fe/example/src/pages/Home.tsx
We've had one partner get confused by all the placeholder pages we scrounged together on the Wingman site. To avoid this, strip down the homepage to link to the Developer Site and Storybook, at least until we have more finalised components to rebuild the individual pages from.
=> Tweak homepage to reflect current state

.changeset/itchy-vans-provide.md, fe/lib/components/LocationSuggest/LocationSuggest.tsx
- ApolloError is an object and can not be used as a string error message. Extract the ApollowError.message to fix the render error.
This issue related to ->  https://trello.com/c/S7Dqon0c/29-improve-ryanair-error-handling-eg-during-job-posting-using-suggestlocations
=> Using error.message

.changeset/blue-bottles-type.md, fe/lib/components/JobCategorySelect/JobCategorySelect.tsx, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx, fe/lib/components/JobCategorySelect/styles.css.ts, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
This PR does the following:
- Updates the text "Other" to "Choose a different category"
- Stack the sub category under the parent category with a linking line
- Removed the label for the sub category when using job category select (doesn't seem necessary anymore)
**Category Suggest:**
**Category Select:**
=> Align category select styling

.changeset/tall-files-glow.md, fe/lib/components/JobCategorySelect/JobCategorySelectInput.tsx, fe/lib/components/JobCategorySelect/styles.css.ts
The linking line between the parent and child category were being hidden behind the card in Ryanair due to its `z-index`. I've gone and removed that and instead just calculated the correct height and width for it, as well as set the curvature to only occur to the bottom left of the border.
=> Fix linking line being hidden for job category select

.github/workflows/release.yml, .github/workflows/validate.yml
The release action was failing because it didn't understand `??`.
https://node.green/#ES2020-features--nullish-coalescing-operator-----
=> Upgrade to Node.js 14 in CI

.changeset/ten-boats-invent.md, fe/lib/components/AdSelectionFallback/AdSelectionFallback.mock.tsx, fe/lib/components/BrandSelect/BrandSelect.mock.tsx, fe/lib/components/JobCategorySelect/JobCategorySelect.mock.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.mock.tsx, fe/lib/components/LocationSuggest/LocationSuggest.mock.tsx, fe/lib/private/MockComponentActions/MockComponentActions.tsx
The existence of Wingman is still a bit mysterious. This adds an explicit link from our `MockComponentActions` to the relevant directory on GitHub. This will allow curious developers to go directly from the mock component on the Developer Site to the Wingman source.
=> Add GitHub links to mock component actions

.changeset/six-spiders-smile.md, fe/lib/components/AdSelectionFallback/AdSelectionFallback.mock.tsx, fe/lib/components/BrandSelect/BrandSelect.mock.tsx, fe/lib/components/JobCategorySelect/JobCategorySelect.mock.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggest.mock.tsx, fe/lib/components/LocationSuggest/LocationSuggest.mock.tsx, fe/lib/components/SalaryDetails/SalaryDetails.mock.tsx, fe/lib/private/MockComponentActions/MockComponentActions.tsx
When this is `false`/`undefined` we still show the "View on GitHub" link which is unlikely what the consumer wants. This repurposes the flag to control both the storybook & GitHub links as a group.
This also lets us tighten the types on our internal `MockComponentActions` to ensure the mock component is providing all the relevant links.
=> Control GitHub links with `showStorybookAction`

.changeset/big-mice-camp.md, fe/lib/components/SalaryDetails/SalaryDetails.mock.tsx
This consists of a multiple controls which makes the `medium` spacing look a bit crowded.
=> Increase spacing on `MockSalaryDetails` actions

.changeset/purple-eggs-wave.md, fe/lib/components/SpecifiedPersonForm/SpecifiedPersonForm.tsx
We have lots of horizontal space on desktop to display the names beside each other. This should free up some precious vertical space on Ryanair.
=> Show `SpecifiedPerson` name components on same row

.changeset/healthy-readers-sneeze.md, fe/lib/components/SpecifiedPersonForm/SpecifiedPersonForm.tsx
This makes little difference on desktop browsers, but causes mobile software keyboards to customise their layout.
=> Set input type for SpecifiedPersonForm email/phone

.changeset/odd-moose-jump.md, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
This is a second fix for the same issue in #656. This doesn't require our callers to be as careful to pass identical props.
- Simplify our querying of job category suggestions. Previously we were using a lazy query and then immediately invoking the query with a `useEffect`. This defeats Apollo's ability to avoid rerunning identical queries.
- Don't reset our selection on every render if the state already contained a selected job category.
=> Don't lose selected job category on re-render

.changeset/quick-eagles-fail.md, fe/lib/components/LocationSuggest/LocationSuggest.tsx
We were driving a lot of Apollo's logic using a series of `useEffect`s. That style is:
- Hard to follow
- Fragile in the case of re-renders (similar to the problems `JobCategorySuggest` had)
- Caused "The user aborted a request" errors to be throw in dev mode
This switches us to `useQuery` instead of `useEffect` + `useState` + `useLazyQuery`.
=> Refactor LocationSuggest to use functional queries

.changeset/quick-eagles-ring.md, fe/lib/components/JobCategorySuggest/JobCategorySuggestChoices.tsx
https://trello.com/c/F3JHJ63H/1600-do-not-prefill-jobcategoryselect-in-jobcategorysuggest
We got feedback from Acendre via the implementation squads that preselecting a category was not ideal in a UX sense.
Have a look for anything else that can be simplified or removed now that this feature is gone. I couldn't see any, but a second pair of eyes might find something.
=> Stop JobCategorySuggest auto-selecting highly-recommended categories

.changeset/many-items-cheer.md, fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx
The `JobCategorySuggest` component had both `initialValue`, and `value` props which made understanding correct usage unintuitive. I've removed the `value` prop because it wasn't wired up to anything internally, and was the simpler fix.
I believe this will require a small change in Ryanair [here](https://github.com/SEEK-Jobs/indie-ryanair-frontend/blob/3b172761fe2f8c3451927ad41b186ad38a11cfbe/src/pages/Posting/positionPosting/PositionPosting.tsx#L534), but this should not require any refactoring, because this prop wasn't wired up to anything.
I've made this a semver major, because it _technically_ breaks the public interface of the component.
=> Remove unused 'value' prop from JobCategorySuggest

fe/lib/components/JobCategorySuggest/JobCategorySuggest.tsx, fe/lib/components/JobCategorySuggest/README.md
https://trello.com/c/TFl6rqmQ/1551-document-initialvalue-prop-of-jobcategorysuggest-component-from-wingman
These docs have slowly drifted out of date and needed a few updates to line them up with the changes we've made to the JobCategorySuggest component.
I've not added a changeset because this is only documentation and reorderings.
=> Update JobCategorySuggest documentation

yarn.lock
🤷‍♀️
`yarn fe start-storybook` was crashing with a `TypeError: (0 , _coreCommon.babelConfig) is not a function` in `@storybook/core-server`, but a relock fixed it.
=> Relock to fix Storybook

.changeset/rotten-mugs-develop.md, fe/lib/components/QuestionnaireBuilder/FormBuilder/components/NewQuestionForm/components/SelectOptions.tsx
You'd have to try really hard to do this in the UI, but this should also serve as documentation.
---
Example with the limit artificially reduced to 3:
| Below limit | At limit
| :-: | :-:
| <img width="457" alt="Screen Shot 2021-12-21 at 8 00 47 am" src="https://user-images.githubusercontent.com/25572311/146832255-05d0ea58-c516-4068-b891-73cafeff45c9.png"> | <img width="457" alt="Screen Shot 2021-12-21 at 8 01 17 am" src="https://user-images.githubusercontent.com/25572311/146832265-c7413233-0426-4f11-9d3c-b765dfe9d0b0.png">
=> Limit question response choices to 99

.changeset/two-cherries-guess.md, fe/lib/components/BrandSelect/BrandSelect.tsx
Need to trigger the onSelect function to send the preselected brand id to the form.
> When you are on the position posting page, fill in required details, then select Standout for the ad type, the UI will preselect the first brand for you. This selected brand is not sent as part of the payload for posting a position or previewing the job ad.
=> Trigger onSelect function for preselecting first brand

.changeset/heavy-readers-act.md, .changeset/three-timers-love.md, fe/lib/components/JobCategoryLookup/JobCategoryLookup.tsx, fe/lib/components/LocationLookup/LocationLookup.tsx, fe/lib/components/SeekApiResponse/SeekApiResponse.stories.tsx, fe/lib/components/SeekApiResponse/SeekApiResponse.tsx, fe/lib/components/SeekApiResponse/__snapshots__/prettyPrintWithoutTypename.test.ts.snap, fe/lib/components/SeekApiResponse/prettyPrintWithoutTypename.test.ts, fe/lib/components/SeekApiResponse/prettyPrintWithoutTypename.ts, fe/lib/index.ts
This now automatically removes `__typename`s.
=> Uplift and export `SeekApiResponse`

.changeset/curvy-laws-drive.md, fe/lib/components/LocationSelectMap/LocationSelectMap.tsx
After using the `LocationSelectMap` outside of a modal I realised that we would likely want the suggestions panel to dismiss when a location is selected. Furthermore, now when a marker is selected after the suggestions have been dismissed, the suggestions will be shown again.
=> fix: LocationSelectMap dismiss/show suggestions behaviour

fe/lib/storybook/controls.tsx, fe/lib/storybook/decorators.tsx
The dynamic loadable approach we had before doesn't work with Braid 32. This gives us an opportunity to simplify our code as we don't need to microoptimise our Storybook.
=> Load Braid themes explicitly in Storybook

.changeset/great-dots-reflect.md, be/src/seekGraph/schema.ts
To fix the connection of sending `Accept-Language` between Ryanair and GraphQL.
=> Add `Accept-Language` header to seek api

.changeset/dirty-nails-jump.md, fe/lib/components/LocationLookup/__fixtures__/location.ts, fe/lib/components/LocationSelectMap/__fixtures__/nearestLocations.ts, fe/lib/components/LocationSuggest/__fixtures__/locationSuggest.ts, fe/lib/components/LocationSuggest/__fixtures__/nearestLocations.ts
Since our mock data does not include `currencies` for location queries, the mock versions of the components which we include in documentation are failing.
=> Update mock location query data to include currencies

.changeset/nasty-zebras-teach.md, be/src/seekGraph/schema.ts
The V1 panel in Ryanair is currently broken after I deprecate the `seekAnzAdvertisementType`.
We should be able to use the deprecated field in the mutation to demo the differnece between v1 and v3 panel.
=> fix: Allow mutation to use the deprecated field in the input

.changeset/slimy-guests-melt.md, fe/lib/components/SalaryDetails/SalaryDetails.tsx
Right now, the minimum and maximum values are managed in the local useState input that is initialized from the props. 
This change is to ensure it got rerendered when the max & min values from the props values were reset
=> Refactor useEffectfulState to cater reset input UI rerendering

.changeset/wise-wolves-hammer.md, fe/lib/components/LocationSuggest/LocationSuggest.stories.tsx, fe/lib/components/LocationSuggest/LocationSuggest.tsx
Adds logic to `LocationSuggest` so that it clears when the `hirerId` changes. This is because the locations returned by the location suggestions query vary depending on the hirer.
=> feat(LocationSuggest): Reset location on hirer change

.changeset/dull-timers-change.md, fe/lib/components/LocationSelectMap/LocationSelectMap.tsx
`Text` sets the right color mode and stops the element from stretching to full width.
=> Wrap `InlineCode` with `Text`
